// Auto-generated by Manic. Do not edit.
// This file is regenerated from app/api/**/index.ts during dev/build.
import { Hono } from 'hono';
import route_health from './health/index';
import route_hello from './hello/index';
import route_timestamp from './timestamp/index';

export const app = new Hono()
  .route('/health', route_health)
  .route('/hello', route_hello)
  .route('/timestamp', route_timestamp);

export type AppType = typeof app;
